# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

services:
  - postgresql

before_script:
   - psql -c 'create database contacts' -U postgres

# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
notifications:
  email: false