
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: vortex
    continueOnError: false
    initialize: false
    tomcat:
      testWhileIdle: true
      validationQuery: SELECT 1
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 10
      min-idle: 2
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 20000
      max-idle: 5
      initial-size: 5
      # Validate the connection before borrowing it from the pool.
      test-on-borrow: true
      remove-abandoned: true
      test-on-connect: true

    schema: classpath:/db/schema-postgres.sql
    data:  classpath:/db/data-postgres.sql

  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
